name: Build Sakinah APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 جلب ملفات الكود
        uses: actions/checkout@v4

      - name: ☕ تثبيت بيئة الجافا
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🐦 تثبيت بيئة فلاتر المستقرة
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: 🔥 إعادة بناء وتحديث مجلد الأندرويد جذرياً
        run: |
          rm -rf android/
          flutter create . --platforms=android --org=com.sakinah

      - name: 🌐 إضافة أذونات الإنترنت التلقائية
        run: |
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET"/>\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>' android/app/src/main/AndroidManifest.xml

      - name: 📦 تحميل المكتبات
        run: flutter pub get

      - name: 🚀 بناء ملف الـ APK النهائي
        run: flutter build apk --release

      - name: 📤 رفع واستخراج ملف التطبيق للتحميل
        uses: actions/upload-artifact@v4
        with:
          name: Sakinah-App-Release
          path: build/app/outputs/flutter-apk/app-release.apk
